[tool.poetry]
name = "index"
version = "0.1.0"
description = ""
authors = ["Ng Guoyou <gyng@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
reverse-geocode = "^1.4.1"
Pillow = "^10.0.1"
exifread = "^3.0.0"
click = "^8.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
