[tool.poetry]
name = "index"
version = "0.1.0"
description = ""
authors = ["Ng Guoyou <gyng@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
reverse-geocode = "^1.4.1"
exifread = "^3.0.0"
click = "^8.1.7"
colorthief = "^0.2.1"
ultralytics = "^8.0.184"
# Bug with PyTorch not handling libcublas
# https://stackoverflow.com/a/76647180
torch = ">=2.0.0, !=2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
