import fs from "node:fs";

type PwaManifest = {
  id?: string;
  start_url?: string;
  scope?: string;
  display?: string;
  display_override?: string[];
  launch_handler?: { client_mode?: string };
  icons?: Array<{ src?: string; sizes?: string; type?: string }>;
};

describe("PWA manifest", () => {
  const manifest = JSON.parse(
    fs.readFileSync("public/manifest.webmanifest", "utf8"),
  ) as PwaManifest;

  it("launches the slideshow as one stable, chrome-free application", () => {
    expect(manifest).toMatchObject({
      id: "/",
      start_url: "/slideshow",
      scope: "/",
      display: "standalone",
      display_override: ["fullscreen", "standalone"],
      launch_handler: { client_mode: "navigate-existing" },
    });
  });

  it("declares install icon sizes", () => {
    expect(manifest.icons).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ src: "/pwa-icon-192.png", sizes: "192x192" }),
        expect.objectContaining({ src: "/pwa-icon-512.png", sizes: "512x512" }),
      ]),
    );
  });

  it("only references PNG icons the build generates", () => {
    // The icon paths are hardcoded independently in three places: ICON_SPECS,
    // this manifest, and the worker's precache list. Renaming one leaves the
    // others pointing at a 404 — and because the worker precaches these, that
    // used to mean it never installed at all. The files themselves are
    // gitignored and generated by `prepare:pwa-icons`, which CI does not run
    // before jest, so this compares declarations rather than the filesystem.
    const { ICON_SPECS } = require("../bin/prepare-pwa-icons.cjs") as {
      ICON_SPECS: Array<{ filename: string; size: number }>;
    };
    const generated = ICON_SPECS.map(({ filename }) => `/${filename}`);

    const manifestPngs = (manifest.icons ?? [])
      .map(({ src }) => src)
      .filter((src): src is string => Boolean(src?.endsWith(".png")));
    expect(manifestPngs.length).toBeGreaterThan(0);
    for (const src of manifestPngs) {
      expect(generated).toContain(src);
    }

    const worker = fs.readFileSync("public/sw.js", "utf8");
    const precacheList = worker.match(/SHELL_STATIC_ASSETS = \[([\s\S]*?)\]/)?.[1] ?? "";
    const precachedPngs = [...precacheList.matchAll(/"([^"]+\.png)"/g)].map(([, src]) => src);
    expect(precachedPngs.length).toBeGreaterThan(0);
    for (const src of precachedPngs) {
      expect(generated).toContain(src);
    }
  });
});
