import nextJest from "next/jest.js";

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: "./",
});

// Add any custom config to be passed to Jest
/** @type {import('jest').Config} */
const config = {
  // Add more setup options before each test is run
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],

  // Keep coverage honest by including production modules even when no test
  // imports them. Type-only files remain in scope but contribute no executable
  // statements.
  collectCoverageFrom: [
    "<rootDir>/License.tsx",
    "<rootDir>/bin/**/*.{cjs,ts}",
    "<rootDir>/components/**/*.{ts,tsx}",
    "<rootDir>/lib/**/*.{ts,tsx}",
    "<rootDir>/pages/**/*.{ts,tsx}",
    "<rootDir>/screens/**/*.{ts,tsx}",
    "<rootDir>/services/**/*.{ts,tsx}",
    "<rootDir>/util/**/*.{ts,tsx}",
    "!<rootDir>/**/*.d.ts",
    "!<rootDir>/**/*.test.{cjs,ts,tsx}",
    // Generated by write-build-manifest.cjs, whose output contract is tested.
    "!<rootDir>/lib/buildVersion.ts",
  ],

  testEnvironment: "node",
  testTimeout: 30000,
  testPathIgnorePatterns: [
    "<rootDir>/.next/",
    "<rootDir>/node_modules/",
    "<rootDir>/tests/", // Ignore Playwright tests
  ],
};

// createJestConfig is exported this way to ensure that next/jest can load the Next.js config which is async
export default createJestConfig(config);
