name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run test:ci
  
  # This does not run on CI because janus is too large a dependency to be installed on GHA
  # 
  # test-index:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./index
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install poetry
  #       run: pipx install poetry
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.12"
  #         cache: "poetry"
  #     - run: poetry install
  #     - run: |
  #         chmod +x ./do-test-index.sh
  #         ./do-test-index.sh
  #       shell: bash
