name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run test:ci
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

# FIXME: Janus fails to be installed on GHA with "git@github.com: Permission denied (publickey)."
# test-index:
#   runs-on: ubuntu-latest
#   defaults:
#     run:
#       working-directory: ./index
#   steps:
#     - uses: actions/checkout@v4
#     - name: Install uv
#       uses: astral-sh/setup-uv@v5
#       with:
#         enable-cache: true
#     - name: Set up Python
#       run: uv python install
#     - name: Install the project
#       run: uv sync --all-extras --dev
#     - run: |
#         chmod +x ./do-test-index.sh
#         ./do-test-index.sh
#       shell: bash
